version: '3'
services:
  httpd:
    container_name: httpd-container
    build: ./docker/httpd
    ports:
      - "80:80"
  tomcat1:
    container_name: tomcat-container1
    build: ./docker/tomcat1
    #    volumes:
    #  - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    expose:
      - "8009"
  tomcat2:
    container_name: tomcat-container2
    build: ./docker/tomcat2
    #    volumes:
    #  - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    expose:
      - "8009"
volumes:
  data: {}
